"""
sisters_invites.py — Sisters of Medusa Invite System

Invite-only membership. Every code is traceable.
Every invite chain is accountable.

Tiers:
  FOUNDER  — unlimited codes per day (you)
  CIRCLE   — 20 codes per day (trusted women you designate)
  MEMBER   — 0/day for first 24hrs, then 5/day for 30 days, then 10/day

Model:
  InviteCode — tracks who generated, who used, when, status

Routes:
  POST /sisters/api/invite/generate  — generate a new code
  POST /sisters/api/invite/revoke    — cancel an unused code
  GET  /sisters/api/invite/mine      — see your codes and their status
  GET  /sisters/api/invite/chain     — see who you've brought in (your invite tree)

Registration (sisters_web.py) updated to require invite code.

Accountability:
  - Every code links inviter → invitee permanently
  - If invitee is suspended, inviter is notified
  - If inviter's account is suspended, all unused codes are auto-revoked
  - Inviter can revoke unused codes at any time

Founder account:
  - First account created is automatically Founder tier
  - Or set SISTERS_FOUNDER_USERNAME in .env to designate on first run

Founded by T.L. Powers · Sisters of Medusa · 2026
"""

import os
import secrets
import string
from datetime import datetime, timezone, date, timedelta
from sqlalchemy import Column, Integer, String, Boolean, DateTime, Date, ForeignKey, Enum
from sqlalchemy.orm import relationship
import enum

from sisters_database import (
    Base, SessionLocal, get_session,
    Sister,
)

FOUNDER_USERNAME = os.environ.get("SISTERS_FOUNDER_USERNAME", "").lower()

# ── Daily limits by tier ───────────────────────────────────────────────────────

class SisterTier(str, enum.Enum):
    FOUNDER = "founder"   # Unlimited
    CIRCLE  = "circle"    # 20/day
    MEMBER  = "member"    # 0 for 24hrs, then 5/day for 30 days, then 10/day

DAILY_LIMITS = {
    SisterTier.FOUNDER: None,   # None = unlimited
    SisterTier.CIRCLE:  20,
    SisterTier.MEMBER:  10,     # after 30 days
}

MEMBER_EARLY_LIMIT   = 5   # days 2–30
MEMBER_WAITING_HOURS = 24  # first 24hrs = 0 codes


# ── InviteCode Model ──────────────────────────────────────────────────────────

class InviteCode(Base):
    """
    A single-use invite code generated by a Sister.

    Lifecycle:
      ACTIVE   → can be used to register
      USED     → registration complete, used_by set
      REVOKED  → cancelled by the generator before use
      EXPIRED  → 7 days elapsed without use

    The invite chain is permanent — even after a code is used,
    the link between inviter and invitee is retained for accountability.
    """
    __tablename__ = "sister_invite_codes"

    CODE_LENGTH  = 12
    TTL_DAYS     = 7

    id           = Column(Integer, primary_key=True, index=True)
    code         = Column(String(20), unique=True, index=True, nullable=False)

    # Who generated it
    generated_by = Column(Integer, ForeignKey("sisters.id"), nullable=False)

    # Who used it (set on registration)
    used_by      = Column(Integer, ForeignKey("sisters.id"), nullable=True)

    # Status
    status       = Column(String(10), default="active")  # active/used/revoked/expired

    # Timing
    created_at   = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    expires_at   = Column(DateTime, nullable=False)
    used_at      = Column(DateTime, nullable=True)

    # Relationships
    generator    = relationship("Sister", foreign_keys=[generated_by])
    invitee      = relationship("Sister", foreign_keys=[used_by])

    @staticmethod
    def generate_code() -> str:
        """
        Generate a readable invite code.
        Format: SSTR-XXXX-XXXX
        Avoids ambiguous characters (0/O, 1/I/l).
        """
        chars = string.ascii_uppercase.replace('O', '').replace('I', '') + \
                string.digits.replace('0', '').replace('1', '')
        part1 = ''.join(secrets.choice(chars) for _ in range(4))
        part2 = ''.join(secrets.choice(chars) for _ in range(4))
        return f"SSTR-{part1}-{part2}"


# ── Sister Tier extension ─────────────────────────────────────────────────────
# We add tier and daily tracking to the Sister model via a separate table
# to avoid modifying the core sister record structure.

class SisterTierRecord(Base):
    """
    Tracks a Sister's tier and daily invite usage.
    Separate from the main Sister model for clean separation.
    """
    __tablename__ = "sister_tiers"

    id             = Column(Integer, primary_key=True)
    sister_id      = Column(Integer, ForeignKey("sisters.id"), unique=True, nullable=False)
    tier           = Column(String(10), default=SisterTier.MEMBER)
    codes_today    = Column(Integer, default=0)
    last_reset     = Column(Date, default=lambda: date.today())

    # Invite tree — who invited this Sister (NULL for founder)
    invited_by     = Column(Integer, ForeignKey("sisters.id"), nullable=True)

    sister         = relationship("Sister", foreign_keys=[sister_id])
    inviter        = relationship("Sister", foreign_keys=[invited_by])


# ── DB Init ───────────────────────────────────────────────────────────────────

def init_invite_tables():
    """Create invite tables. Call alongside init_db()."""
    from sisters_database import engine
    Base.metadata.create_all(bind=engine)
    print("[Sisters] Invite tables initialized.")


# ── Tier helpers ──────────────────────────────────────────────────────────────

def get_or_create_tier(session, sister_id: int) -> SisterTierRecord:
    """Get or create a tier record for a Sister."""
    record = session.query(SisterTierRecord).filter(
        SisterTierRecord.sister_id == sister_id
    ).first()
    if not record:
        record = SisterTierRecord(sister_id=sister_id, tier=SisterTier.MEMBER)
        session.add(record)
        session.flush()
    return record


def reset_daily_if_needed(record: SisterTierRecord):
    """Reset daily code count if it's a new UTC day."""
    today = date.today()
    if record.last_reset != today:
        record.codes_today = 0
        record.last_reset  = today


def get_daily_limit(record: SisterTierRecord, sister: Sister) -> int | None:
    """
    Get the daily invite limit for this Sister.
    Returns None for unlimited (Founder).
    """
    if record.tier == SisterTier.FOUNDER:
        return None  # Unlimited

    if record.tier == SisterTier.CIRCLE:
        return DAILY_LIMITS[SisterTier.CIRCLE]

    # MEMBER tier — check account age
    now = datetime.now(timezone.utc)
    age_hours = (now - sister.joined_at).total_seconds() / 3600

    if age_hours < MEMBER_WAITING_HOURS:
        return 0  # Waiting period — no codes yet

    age_days = age_hours / 24
    if age_days <= 30:
        return MEMBER_EARLY_LIMIT  # Days 2–30: 5/day

    return DAILY_LIMITS[SisterTier.MEMBER]  # After 30 days: 10/day


def can_generate_code(sister_id: int) -> dict:
    """
    Check whether this Sister can generate a new invite code right now.
    Returns {"ok": True} or {"ok": False, "error": ..., "resets_in": ...}
    """
    session = get_session()
    try:
        sister = session.query(Sister).filter(Sister.id == sister_id).first()
        if not sister:
            return {"ok": False, "error": "Account not found."}
        if sister.is_suspended:
            return {"ok": False, "error": "Account suspended."}

        record = get_or_create_tier(session, sister_id)
        reset_daily_if_needed(record)
        session.commit()

        limit = get_daily_limit(record, sister)

        if limit is None:
            return {"ok": True, "limit": None, "used_today": record.codes_today}

        if limit == 0:
            # Still in waiting period
            now = datetime.now(timezone.utc)
            wait_ends = sister.joined_at + timedelta(hours=MEMBER_WAITING_HOURS)
            hours_left = max(0, (wait_ends - now).total_seconds() / 3600)
            return {
                "ok":        False,
                "error":     f"New members can generate invite codes after 24 hours. "
                             f"{int(hours_left)}h remaining.",
                "resets_in": int(hours_left * 3600),
            }

        if record.codes_today >= limit:
            # Calculate seconds until midnight UTC
            now = datetime.now(timezone.utc)
            tomorrow = datetime.combine(
                date.today() + timedelta(days=1),
                datetime.min.time()
            ).replace(tzinfo=timezone.utc)
            secs = int((tomorrow - now).total_seconds())
            return {
                "ok":        False,
                "error":     f"Daily invite limit reached ({limit}/day). "
                             f"Resets at midnight UTC.",
                "resets_in": secs,
                "limit":     limit,
                "used_today": record.codes_today,
            }

        return {
            "ok":        True,
            "limit":     limit,
            "used_today": record.codes_today,
            "remaining": limit - record.codes_today,
        }

    except Exception as e:
        print(f"[Sisters] can_generate_code error: {e}")
        return {"ok": False, "error": "Could not check invite limit."}
    finally:
        session.close()


# ── Core invite functions ─────────────────────────────────────────────────────

def generate_invite_code(sister_id: int) -> dict:
    """
    Generate a new invite code for this Sister.
    Returns {"ok": True, "code": "SSTR-XXXX-XXXX", ...} or error.
    """
    # Check eligibility first
    check = can_generate_code(sister_id)
    if not check["ok"]:
        return check

    session = get_session()
    try:
        now = datetime.now(timezone.utc)

        # Generate unique code
        for _ in range(10):  # Max attempts to avoid collision
            code_str = InviteCode.generate_code()
            if not session.query(InviteCode).filter(
                InviteCode.code == code_str
            ).first():
                break
        else:
            return {"ok": False, "error": "Could not generate unique code. Try again."}

        invite = InviteCode(
            code         = code_str,
            generated_by = sister_id,
            status       = "active",
            created_at   = now,
            expires_at   = now + timedelta(days=InviteCode.TTL_DAYS),
        )
        session.add(invite)

        # Increment daily count
        record = get_or_create_tier(session, sister_id)
        reset_daily_if_needed(record)
        if check["limit"] is not None:  # Don't track for unlimited (founder)
            record.codes_today += 1

        session.commit()

        limit    = check.get("limit")
        used     = record.codes_today
        remaining = None if limit is None else max(0, limit - used)

        return {
            "ok":        True,
            "code":      code_str,
            "expires":   invite.expires_at.isoformat(),
            "remaining_today": remaining,
        }

    except Exception as e:
        session.rollback()
        print(f"[Sisters] generate_invite_code error: {e}")
        return {"ok": False, "error": "Failed to generate code. Try again."}
    finally:
        session.close()


def revoke_invite_code(code_str: str, sister_id: int) -> dict:
    """
    Revoke an unused invite code.
    Only the generator can revoke their own codes.
    """
    session = get_session()
    try:
        invite = session.query(InviteCode).filter(
            InviteCode.code         == code_str,
            InviteCode.generated_by == sister_id,
            InviteCode.status       == "active",
        ).first()

        if not invite:
            return {"ok": False,
                    "error": "Code not found or already used/revoked."}

        invite.status = "revoked"
        session.commit()
        return {"ok": True, "code": code_str}

    except Exception as e:
        session.rollback()
        print(f"[Sisters] revoke_invite_code error: {e}")
        return {"ok": False, "error": "Failed to revoke code."}
    finally:
        session.close()


def get_my_codes(sister_id: int) -> dict:
    """
    Get all invite codes generated by this Sister,
    plus today's usage and limit.
    """
    session = get_session()
    try:
        sister = session.query(Sister).filter(Sister.id == sister_id).first()
        if not sister:
            return {"ok": False, "error": "Account not found."}

        record = get_or_create_tier(session, sister_id)
        reset_daily_if_needed(record)
        session.commit()

        limit     = get_daily_limit(record, sister)
        remaining = None if limit is None else max(0, limit - record.codes_today)

        # Expire stale active codes
        now = datetime.now(timezone.utc)
        stale = session.query(InviteCode).filter(
            InviteCode.generated_by == sister_id,
            InviteCode.status       == "active",
            InviteCode.expires_at   <= now,
        ).all()
        for s in stale:
            s.status = "expired"
        if stale:
            session.commit()

        # Fetch all codes
        codes = session.query(InviteCode).filter(
            InviteCode.generated_by == sister_id
        ).order_by(InviteCode.created_at.desc()).limit(50).all()

        code_list = []
        for c in codes:
            invitee_name = None
            if c.used_by:
                invitee = session.query(Sister).filter(
                    Sister.id == c.used_by).first()
                invitee_name = invitee.display_name if invitee else "Unknown"

            code_list.append({
                "code":         c.code,
                "status":       c.status,
                "created_at":   c.created_at.isoformat(),
                "expires_at":   c.expires_at.isoformat(),
                "used_at":      c.used_at.isoformat() if c.used_at else None,
                "used_by_name": invitee_name,
            })

        return {
            "ok":             True,
            "tier":           record.tier,
            "codes_today":    record.codes_today,
            "daily_limit":    limit,
            "remaining_today": remaining,
            "codes":          code_list,
        }

    except Exception as e:
        print(f"[Sisters] get_my_codes error: {e}")
        return {"ok": False, "error": "Failed to load codes."}
    finally:
        session.close()


def get_my_invite_tree(sister_id: int) -> dict:
    """
    Get the invite tree — who this Sister has brought into the network.
    Shows direct invitees only (not recursive).
    """
    session = get_session()
    try:
        # Find all codes this Sister generated that were used
        used_codes = session.query(InviteCode).filter(
            InviteCode.generated_by == sister_id,
            InviteCode.status       == "used",
            InviteCode.used_by      != None,
        ).all()

        tree = []
        for code in used_codes:
            invitee = session.query(Sister).filter(
                Sister.id == code.used_by).first()
            if invitee:
                # Count how many that invitee has brought in
                their_invites = session.query(InviteCode).filter(
                    InviteCode.generated_by == invitee.id,
                    InviteCode.status       == "used",
                ).count()

                tree.append({
                    "display_name":  invitee.display_name,
                    "joined_at":     invitee.joined_at.isoformat(),
                    "is_active":     invitee.is_network_active,
                    "is_suspended":  invitee.is_suspended,
                    "they_invited":  their_invites,
                })

        return {
            "ok":    True,
            "total": len(tree),
            "tree":  tree,
        }

    except Exception as e:
        print(f"[Sisters] get_my_invite_tree error: {e}")
        return {"ok": False, "error": "Failed to load invite tree."}
    finally:
        session.close()


def validate_and_use_invite_code(code_str: str,
                                  new_sister_id: int,
                                  session) -> dict:
    """
    Validate an invite code during registration and mark it used.
    Called inside the registration transaction.
    Returns {"ok": True, "inviter_id": ...} or error.
    """
    now    = datetime.now(timezone.utc)
    invite = session.query(InviteCode).filter(
        InviteCode.code    == code_str.upper().strip(),
        InviteCode.status  == "active",
        InviteCode.expires_at > now,
    ).first()

    if not invite:
        return {"ok": False,
                "error": "Invalid or expired invite code. "
                         "Ask a Sister for a fresh one."}

    # Check inviter isn't suspended
    inviter = session.query(Sister).filter(
        Sister.id == invite.generated_by
    ).first()

    if not inviter or inviter.is_suspended:
        return {"ok": False,
                "error": "This invite code is no longer valid."}

    # Mark used
    invite.status  = "used"
    invite.used_by = new_sister_id
    invite.used_at = now

    # Link invitee's tier record to inviter
    tier_record = SisterTierRecord(
        sister_id  = new_sister_id,
        tier       = SisterTier.MEMBER,
        invited_by = inviter.id,
    )
    session.add(tier_record)

    return {"ok": True, "inviter_id": inviter.id}


def revoke_all_codes_for_suspended(sister_id: int):
    """
    When a Sister is suspended, revoke all her unused codes.
    Called from the moderation system.
    """
    session = get_session()
    try:
        unused = session.query(InviteCode).filter(
            InviteCode.generated_by == sister_id,
            InviteCode.status       == "active",
        ).all()
        for code in unused:
            code.status = "revoked"
        session.commit()
        print(f"[Sisters] Revoked {len(unused)} codes for suspended sister {sister_id}.")
    except Exception as e:
        session.rollback()
        print(f"[Sisters] revoke_all_codes_for_suspended error: {e}")
    finally:
        session.close()


def set_founder(username: str) -> dict:
    """
    Designate a Sister as Founder tier — unlimited codes, permanent.
    Called on first run or when SISTERS_FOUNDER_USERNAME is set.
    """
    session = get_session()
    try:
        sister = session.query(Sister).filter(
            Sister.username == username.lower().strip()
        ).first()
        if not sister:
            return {"ok": False, "error": f"Sister '{username}' not found."}

        record = get_or_create_tier(session, sister.id)
        record.tier = SisterTier.FOUNDER
        session.commit()
        print(f"[Sisters] {username} designated as Founder.")
        return {"ok": True}

    except Exception as e:
        session.rollback()
        print(f"[Sisters] set_founder error: {e}")
        return {"ok": False, "error": "Failed to set founder."}
    finally:
        session.close()


def set_circle(username: str) -> dict:
    """Designate a Sister as Circle tier — 20 codes/day."""
    session = get_session()
    try:
        sister = session.query(Sister).filter(
            Sister.username == username.lower().strip()
        ).first()
        if not sister:
            return {"ok": False, "error": f"Sister '{username}' not found."}

        record = get_or_create_tier(session, sister.id)
        record.tier = SisterTier.CIRCLE
        session.commit()
        print(f"[Sisters] {username} designated as Circle member.")
        return {"ok": True}

    except Exception as e:
        session.rollback()
        print(f"[Sisters] set_circle error: {e}")
        return {"ok": False, "error": "Failed to set circle tier."}
    finally:
        session.close()
